html:
  css: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'
filter:
  message:
      # Filter by exact match
    - "Message to filter"
    - Oter message to filter
    - Unused argument 'request'
  message_re:
      # Regexps to filter
    - 'Exactly one space required after comma.*'
    - 'Exactly one space required before assignment.*'
